version: '3.1'
services:
  smartcourse-testing:
    container_name: 'smartcourse-testing'
    build:
      context: .
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${LOCAL_SQL_PASSWORD}
      ACCEPT_EULA: "Y"
    healthcheck:
      test: sqlcmd -S localhost,1433 -U SA -P "$SA_PASSWORD" -Q 'select * from smartcourse-testing.testdb.tables'

